name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_target:
          - StandaloneWindows64
          - WebGL
    steps:
      - name: Check out unity project
        uses: actions/checkout@v4

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          # 今回は WebGL ビルドを行いたいため WebGL を指定する
          # WebGL 以外の指定可能な値は下記に記載の値が利用可能
          # ref: https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: ${{ matrix.build_target }}

          unityVersion: 2020.3.5f1

      # Builder で出力した WebGL ビルドをアーティファクトでダウンロード可能にする
      - name: Upload Pre-Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
