name: Build

on:
  push:
    branches: main
  pull_request:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform:
          - StandaloneWindows64
          - Android
          - WebGL
        unity-version:
          - 2023.2.5f1

    steps:
      - name: Check out unity project ${{ github.workflow }}-${{ github.ref }}
        uses: actions/checkout@v4

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.target-platform }}
          unityVersion: ${{ matrix.unity-version }}

      - name: Upload the Build for ${{ matrix.target-platform }}
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.target-platform }}
          path: build
