name: Lint

on:
  push:
    branches: main
#    branches: develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: ./Assets/.*.cs
          FILTER_REGEX_EXCLUDE: ./Assets/TextMesh Pro/.*
