name: Lint

on:
  push:
    branches: main
#    branches: develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out unity project
        uses: actions/checkout@v4

      - name: Super linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Git が無視するファイルを無視するかどうか
          IGNORE_GITIGNORED_FILES: true
          # 変更ファイル以外のすべてのファイルをチェック対象とするか
          VALIDATE_ALL_CODEBASE: true
          # セキュリティチェックを無効化
          VALIDATE_CHECKOV: false
          # 重複チェックを無効化
          VALIDATE_JSCPD: false
          FILTER_REGEX_INCLUDE: '/Assets/.*\.cs'
          FILTER_REGEX_EXCLUDE: '/Assets/TextMesh Pro/.*'
