name: Spell Check

permissions: read-all

on:
  push:
    branches: main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Spell Check Repo
      uses: crate-ci/typos@v1.29.5
